### ISSUE TITLE
npm command to run the application

### ISSUE THREAD

**Issue by alessandra-souza** [SAP/ui5-webcomponents-sample-vue#5]
npm start didn't work for me. Only when I used **npm run serve**, the app actually started.

**Comment by adrian-bobev** [comment]
@alessandra-souza I saw that you have committed a fix for the README.md file but Pull Request that you made is for your fork's mater branch. 

Pull Request to this repository is also welcome

**Comment by adrian-bobev** [comment]
Thank you for contribution
